// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Hxk4WFhjIWRD0lKHVKFJ5EIIeN_pdTs',
    appId: '1:534221312754:web:23776f119b11e460a5f66b',
    messagingSenderId: '534221312754',
    projectId: 'task-6ba3c',
    authDomain: 'task-6ba3c.firebaseapp.com',
    storageBucket: 'task-6ba3c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLnBr6qggLwTmiN-PGs2DK9YeRuLwUVvg',
    appId: '1:534221312754:android:2e6b98634859b34ca5f66b',
    messagingSenderId: '534221312754',
    projectId: 'task-6ba3c',
    storageBucket: 'task-6ba3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl2fVnpq99vNsTdoVyaDWFX3zYODsIxwI',
    appId: '1:534221312754:ios:49247fce856f1135a5f66b',
    messagingSenderId: '534221312754',
    projectId: 'task-6ba3c',
    storageBucket: 'task-6ba3c.appspot.com',
    iosBundleId: 'com.example.task1',
  );
}
